// This file was automatically generated by tools/update-node-prototypes.py
// All changes to this file will be lost

#pragma once

namespace vx {
inline namespace visualizer_prop {
class SlicePropertiesEntry;
class SlicePropertiesBase;
class SlicePropertiesCopy;
class SliceProperties;
}  // namespace visualizer_prop
}  // namespace vx
