// This file was automatically generated by tools/update-node-prototypes.py
// All changes to this file will be lost

#pragma once

namespace vx {
inline namespace filter_prop {
class ColorizeLabeledSurfacePropertiesEntry;
class ColorizeLabeledSurfacePropertiesBase;
class ColorizeLabeledSurfacePropertiesCopy;
class ColorizeLabeledSurfaceProperties;
}  // namespace filter_prop
inline namespace filter_prop {
class ColorizeSurfaceFromAttributePropertiesEntry;
class ColorizeSurfaceFromAttributePropertiesBase;
class ColorizeSurfaceFromAttributePropertiesCopy;
class ColorizeSurfaceFromAttributeProperties;
}  // namespace filter_prop
inline namespace filter_prop {
class CreateSurfacePropertiesEntry;
class CreateSurfacePropertiesBase;
class CreateSurfacePropertiesCopy;
class CreateSurfaceProperties;
}  // namespace filter_prop
inline namespace filter_prop {
class TableFilterPropertiesEntry;
class TableFilterPropertiesBase;
class TableFilterPropertiesCopy;
class TableFilterProperties;
}  // namespace filter_prop
}  // namespace vx
