// This file was automatically generated by tools/update-node-prototypes.py
// All changes to this file will be lost

#pragma once

namespace vx {
inline namespace visualizer_prop {
class TomographyRawDataPropertiesEntry;
class TomographyRawDataPropertiesBase;
class TomographyRawDataPropertiesCopy;
class TomographyRawDataProperties;
}  // namespace visualizer_prop
}  // namespace vx
