// This file was automatically generated by tools/update-node-prototypes.py
// All changes to this file will be lost

#pragma once

namespace vx {
inline namespace object3d_prop {
class Test3DObjectPropertiesEntry;
class Test3DObjectPropertiesBase;
class Test3DObjectPropertiesCopy;
class Test3DObjectProperties;
}  // namespace object3d_prop
inline namespace object3d_prop {
class GeometricPrimitivePropertiesEntry;
class GeometricPrimitivePropertiesBase;
class GeometricPrimitivePropertiesCopy;
class GeometricPrimitiveProperties;
}  // namespace object3d_prop
inline namespace object3d_prop {
class GridPropertiesEntry;
class GridPropertiesBase;
class GridPropertiesCopy;
class GridProperties;
}  // namespace object3d_prop
inline namespace object3d_prop {
class PlanePropertiesEntry;
class PlanePropertiesBase;
class PlanePropertiesCopy;
class PlaneProperties;
}  // namespace object3d_prop
inline namespace object3d_prop {
class SurfacePropertiesEntry;
class SurfacePropertiesBase;
class SurfacePropertiesCopy;
class SurfaceProperties;
}  // namespace object3d_prop
inline namespace visualizer_prop {
class View3DPropertiesEntry;
class View3DPropertiesBase;
class View3DPropertiesCopy;
class View3DProperties;
}  // namespace visualizer_prop
inline namespace visualizer_prop {
class VolumeRenderingPropertiesEntry;
class VolumeRenderingPropertiesBase;
class VolumeRenderingPropertiesCopy;
class VolumeRenderingProperties;
}  // namespace visualizer_prop
}  // namespace vx
