// This file was automatically generated by tools/update-debug-options.py
// All changes to this file will be lost

#include "DebugOptions.hpp"

namespace vx {
namespace debug_option_impl {
vx::DebugOptionBool Log_SurfaceBoundingBox_option("Log.SurfaceBoundingBox");
}
}  // namespace vx

vx::DebugOptionBool* vx::debug_option::Log_SurfaceBoundingBox() {
  return &vx::debug_option_impl::Log_SurfaceBoundingBox_option;
}

QList<vx::DebugOption*> vx::getVoxieBackendDebugOptions() {
  return {
      vx::debug_option::Log_SurfaceBoundingBox(),
  };
}
