// This file was automatically generated by tools/update-debug-options.py
// All changes to this file will be lost

#pragma once

#include <VoxieClient/DebugOption.hpp>

#include <VoxieBackend/VoxieBackend.hpp>

namespace vx {
namespace debug_option {
VOXIEBACKEND_EXPORT vx::DebugOptionBool* Log_SurfaceBoundingBox();
}

VOXIEBACKEND_EXPORT QList<vx::DebugOption*> getVoxieBackendDebugOptions();
}  // namespace vx
