/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -p Main/dbusproxies
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "Main/dbusproxies.hpp"

/*
 * Implementation of interface class DeUni_stuttgartVoxieClientInterface
 */

DeUni_stuttgartVoxieClientInterface::DeUni_stuttgartVoxieClientInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

DeUni_stuttgartVoxieClientInterface::~DeUni_stuttgartVoxieClientInterface()
{
}

/*
 * Implementation of interface class DeUni_stuttgartVoxieDataSetInterface
 */

DeUni_stuttgartVoxieDataSetInterface::DeUni_stuttgartVoxieDataSetInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

DeUni_stuttgartVoxieDataSetInterface::~DeUni_stuttgartVoxieDataSetInterface()
{
}

/*
 * Implementation of interface class DeUni_stuttgartVoxieGuiInterface
 */

DeUni_stuttgartVoxieGuiInterface::DeUni_stuttgartVoxieGuiInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

DeUni_stuttgartVoxieGuiInterface::~DeUni_stuttgartVoxieGuiInterface()
{
}

/*
 * Implementation of interface class DeUni_stuttgartVoxieImageInterface
 */

DeUni_stuttgartVoxieImageInterface::DeUni_stuttgartVoxieImageInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

DeUni_stuttgartVoxieImageInterface::~DeUni_stuttgartVoxieImageInterface()
{
}

/*
 * Implementation of interface class DeUni_stuttgartVoxieImporterInterface
 */

DeUni_stuttgartVoxieImporterInterface::DeUni_stuttgartVoxieImporterInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

DeUni_stuttgartVoxieImporterInterface::~DeUni_stuttgartVoxieImporterInterface()
{
}

/*
 * Implementation of interface class DeUni_stuttgartVoxieLoaderInterface
 */

DeUni_stuttgartVoxieLoaderInterface::DeUni_stuttgartVoxieLoaderInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

DeUni_stuttgartVoxieLoaderInterface::~DeUni_stuttgartVoxieLoaderInterface()
{
}

/*
 * Implementation of interface class DeUni_stuttgartVoxiePluginInterface
 */

DeUni_stuttgartVoxiePluginInterface::DeUni_stuttgartVoxiePluginInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

DeUni_stuttgartVoxiePluginInterface::~DeUni_stuttgartVoxiePluginInterface()
{
}

/*
 * Implementation of interface class DeUni_stuttgartVoxiePluginMemberInterface
 */

DeUni_stuttgartVoxiePluginMemberInterface::DeUni_stuttgartVoxiePluginMemberInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

DeUni_stuttgartVoxiePluginMemberInterface::~DeUni_stuttgartVoxiePluginMemberInterface()
{
}

/*
 * Implementation of interface class DeUni_stuttgartVoxiePluginsExamplePluginTheSphereGeneratorInterface
 */

DeUni_stuttgartVoxiePluginsExamplePluginTheSphereGeneratorInterface::DeUni_stuttgartVoxiePluginsExamplePluginTheSphereGeneratorInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

DeUni_stuttgartVoxiePluginsExamplePluginTheSphereGeneratorInterface::~DeUni_stuttgartVoxiePluginsExamplePluginTheSphereGeneratorInterface()
{
}

/*
 * Implementation of interface class DeUni_stuttgartVoxieSliceInterface
 */

DeUni_stuttgartVoxieSliceInterface::DeUni_stuttgartVoxieSliceInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

DeUni_stuttgartVoxieSliceInterface::~DeUni_stuttgartVoxieSliceInterface()
{
}

/*
 * Implementation of interface class DeUni_stuttgartVoxieSliceDataVisualizerInterface
 */

DeUni_stuttgartVoxieSliceDataVisualizerInterface::DeUni_stuttgartVoxieSliceDataVisualizerInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

DeUni_stuttgartVoxieSliceDataVisualizerInterface::~DeUni_stuttgartVoxieSliceDataVisualizerInterface()
{
}

/*
 * Implementation of interface class DeUni_stuttgartVoxieVisualizerFactoryInterface
 */

DeUni_stuttgartVoxieVisualizerFactoryInterface::DeUni_stuttgartVoxieVisualizerFactoryInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

DeUni_stuttgartVoxieVisualizerFactoryInterface::~DeUni_stuttgartVoxieVisualizerFactoryInterface()
{
}

/*
 * Implementation of interface class DeUni_stuttgartVoxieVolumeDataVisualizerInterface
 */

DeUni_stuttgartVoxieVolumeDataVisualizerInterface::DeUni_stuttgartVoxieVolumeDataVisualizerInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

DeUni_stuttgartVoxieVolumeDataVisualizerInterface::~DeUni_stuttgartVoxieVolumeDataVisualizerInterface()
{
}

/*
 * Implementation of interface class DeUni_stuttgartVoxieVoxelDataInterface
 */

DeUni_stuttgartVoxieVoxelDataInterface::DeUni_stuttgartVoxieVoxelDataInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

DeUni_stuttgartVoxieVoxelDataInterface::~DeUni_stuttgartVoxieVoxelDataInterface()
{
}

/*
 * Implementation of interface class DeUni_stuttgartVoxieVoxieInterface
 */

DeUni_stuttgartVoxieVoxieInterface::DeUni_stuttgartVoxieVoxieInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

DeUni_stuttgartVoxieVoxieInterface::~DeUni_stuttgartVoxieVoxieInterface()
{
}
