#!/bin/sh

set -e

SCRIPT="$(readlink -v -f -- "$0")"
VOXIE_DIR="${SCRIPT%/*}"

# Add $VOXIE_DIR/lib directory to LD_LIBRARY_PATH / DYLD_LIBRARY_PATH
# TODO: Use rpath
VOXIE_LIB_PATH="$VOXIE_DIR/lib"
export LD_LIBRARY_PATH="$VOXIE_LIB_PATH${LD_LIBRARY_PATH+:$LD_LIBRARY_PATH}"

# Run voxie
exec "$VOXIE_DIR/bin/voxie" "$@"
