#!/bin/sh

set -e

git ls-tree -r HEAD src -z --name-only |
    grep -z '\.hpp$\|\.cpp$' |
    grep -z -v '^src/ExtFileHdf5/.*/\|^src/VoxieBackend/OpenCL/opencl-patched\.hpp' |
    xargs -0 clang-format -i --
