/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -p tmp-dbus/DBusProxies -a
 * tmp-dbus/DBusAdaptors
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "VoxieClient/DBusProxies.hpp"

/*
 * Implementation of interface class DeUni_stuttgartVoxieBufferInterface
 */

DeUni_stuttgartVoxieBufferInterface::DeUni_stuttgartVoxieBufferInterface(
    const QString& service, const QString& path,
    const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieBufferInterface::~DeUni_stuttgartVoxieBufferInterface() {}

/*
 * Implementation of interface class DeUni_stuttgartVoxieBufferTypeInterface
 */

DeUni_stuttgartVoxieBufferTypeInterface::
    DeUni_stuttgartVoxieBufferTypeInterface(const QString& service,
                                            const QString& path,
                                            const QDBusConnection& connection,
                                            QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieBufferTypeInterface::
    ~DeUni_stuttgartVoxieBufferTypeInterface() {}

/*
 * Implementation of interface class DeUni_stuttgartVoxieClientInterface
 */

DeUni_stuttgartVoxieClientInterface::DeUni_stuttgartVoxieClientInterface(
    const QString& service, const QString& path,
    const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieClientInterface::~DeUni_stuttgartVoxieClientInterface() {}

/*
 * Implementation of interface class DeUni_stuttgartVoxieClientManagerInterface
 */

DeUni_stuttgartVoxieClientManagerInterface::
    DeUni_stuttgartVoxieClientManagerInterface(
        const QString& service, const QString& path,
        const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieClientManagerInterface::
    ~DeUni_stuttgartVoxieClientManagerInterface() {}

/*
 * Implementation of interface class DeUni_stuttgartVoxieComponentInterface
 */

DeUni_stuttgartVoxieComponentInterface::DeUni_stuttgartVoxieComponentInterface(
    const QString& service, const QString& path,
    const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieComponentInterface::
    ~DeUni_stuttgartVoxieComponentInterface() {}

/*
 * Implementation of interface class
 * DeUni_stuttgartVoxieComponentContainerInterface
 */

DeUni_stuttgartVoxieComponentContainerInterface::
    DeUni_stuttgartVoxieComponentContainerInterface(
        const QString& service, const QString& path,
        const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieComponentContainerInterface::
    ~DeUni_stuttgartVoxieComponentContainerInterface() {}

/*
 * Implementation of interface class DeUni_stuttgartVoxieContainerDataInterface
 */

DeUni_stuttgartVoxieContainerDataInterface::
    DeUni_stuttgartVoxieContainerDataInterface(
        const QString& service, const QString& path,
        const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieContainerDataInterface::
    ~DeUni_stuttgartVoxieContainerDataInterface() {}

/*
 * Implementation of interface class DeUni_stuttgartVoxieDataInterface
 */

DeUni_stuttgartVoxieDataInterface::DeUni_stuttgartVoxieDataInterface(
    const QString& service, const QString& path,
    const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieDataInterface::~DeUni_stuttgartVoxieDataInterface() {}

/*
 * Implementation of interface class DeUni_stuttgartVoxieDataNodeInterface
 */

DeUni_stuttgartVoxieDataNodeInterface::DeUni_stuttgartVoxieDataNodeInterface(
    const QString& service, const QString& path,
    const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieDataNodeInterface::
    ~DeUni_stuttgartVoxieDataNodeInterface() {}

/*
 * Implementation of interface class DeUni_stuttgartVoxieDataObjectInterface
 */

DeUni_stuttgartVoxieDataObjectInterface::
    DeUni_stuttgartVoxieDataObjectInterface(const QString& service,
                                            const QString& path,
                                            const QDBusConnection& connection,
                                            QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieDataObjectInterface::
    ~DeUni_stuttgartVoxieDataObjectInterface() {}

/*
 * Implementation of interface class DeUni_stuttgartVoxieDataPropertyInterface
 */

DeUni_stuttgartVoxieDataPropertyInterface::
    DeUni_stuttgartVoxieDataPropertyInterface(const QString& service,
                                              const QString& path,
                                              const QDBusConnection& connection,
                                              QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieDataPropertyInterface::
    ~DeUni_stuttgartVoxieDataPropertyInterface() {}

/*
 * Implementation of interface class DeUni_stuttgartVoxieDataVersionInterface
 */

DeUni_stuttgartVoxieDataVersionInterface::
    DeUni_stuttgartVoxieDataVersionInterface(const QString& service,
                                             const QString& path,
                                             const QDBusConnection& connection,
                                             QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieDataVersionInterface::
    ~DeUni_stuttgartVoxieDataVersionInterface() {}

/*
 * Implementation of interface class DeUni_stuttgartVoxieDebugOptionInterface
 */

DeUni_stuttgartVoxieDebugOptionInterface::
    DeUni_stuttgartVoxieDebugOptionInterface(const QString& service,
                                             const QString& path,
                                             const QDBusConnection& connection,
                                             QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieDebugOptionInterface::
    ~DeUni_stuttgartVoxieDebugOptionInterface() {}

/*
 * Implementation of interface class DeUni_stuttgartVoxieDynamicObjectInterface
 */

DeUni_stuttgartVoxieDynamicObjectInterface::
    DeUni_stuttgartVoxieDynamicObjectInterface(
        const QString& service, const QString& path,
        const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieDynamicObjectInterface::
    ~DeUni_stuttgartVoxieDynamicObjectInterface() {}

/*
 * Implementation of interface class
 * DeUni_stuttgartVoxieEventListDataAccessorInterface
 */

DeUni_stuttgartVoxieEventListDataAccessorInterface::
    DeUni_stuttgartVoxieEventListDataAccessorInterface(
        const QString& service, const QString& path,
        const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieEventListDataAccessorInterface::
    ~DeUni_stuttgartVoxieEventListDataAccessorInterface() {}

/*
 * Implementation of interface class
 * DeUni_stuttgartVoxieEventListDataAccessorOperationsInterface
 */

DeUni_stuttgartVoxieEventListDataAccessorOperationsInterface::
    DeUni_stuttgartVoxieEventListDataAccessorOperationsInterface(
        const QString& service, const QString& path,
        const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieEventListDataAccessorOperationsInterface::
    ~DeUni_stuttgartVoxieEventListDataAccessorOperationsInterface() {}

/*
 * Implementation of interface class
 * DeUni_stuttgartVoxieEventListDataBufferInterface
 */

DeUni_stuttgartVoxieEventListDataBufferInterface::
    DeUni_stuttgartVoxieEventListDataBufferInterface(
        const QString& service, const QString& path,
        const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieEventListDataBufferInterface::
    ~DeUni_stuttgartVoxieEventListDataBufferInterface() {}

/*
 * Implementation of interface class DeUni_stuttgartVoxieExporterInterface
 */

DeUni_stuttgartVoxieExporterInterface::DeUni_stuttgartVoxieExporterInterface(
    const QString& service, const QString& path,
    const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieExporterInterface::
    ~DeUni_stuttgartVoxieExporterInterface() {}

/*
 * Implementation of interface class DeUni_stuttgartVoxieExtensionInterface
 */

DeUni_stuttgartVoxieExtensionInterface::DeUni_stuttgartVoxieExtensionInterface(
    const QString& service, const QString& path,
    const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieExtensionInterface::
    ~DeUni_stuttgartVoxieExtensionInterface() {}

/*
 * Implementation of interface class
 * DeUni_stuttgartVoxieExternalDataUpdateInterface
 */

DeUni_stuttgartVoxieExternalDataUpdateInterface::
    DeUni_stuttgartVoxieExternalDataUpdateInterface(
        const QString& service, const QString& path,
        const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieExternalDataUpdateInterface::
    ~DeUni_stuttgartVoxieExternalDataUpdateInterface() {}

/*
 * Implementation of interface class
 * DeUni_stuttgartVoxieExternalOperationInterface
 */

DeUni_stuttgartVoxieExternalOperationInterface::
    DeUni_stuttgartVoxieExternalOperationInterface(
        const QString& service, const QString& path,
        const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieExternalOperationInterface::
    ~DeUni_stuttgartVoxieExternalOperationInterface() {}

/*
 * Implementation of interface class
 * DeUni_stuttgartVoxieExternalOperationExportInterface
 */

DeUni_stuttgartVoxieExternalOperationExportInterface::
    DeUni_stuttgartVoxieExternalOperationExportInterface(
        const QString& service, const QString& path,
        const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieExternalOperationExportInterface::
    ~DeUni_stuttgartVoxieExternalOperationExportInterface() {}

/*
 * Implementation of interface class
 * DeUni_stuttgartVoxieExternalOperationImportInterface
 */

DeUni_stuttgartVoxieExternalOperationImportInterface::
    DeUni_stuttgartVoxieExternalOperationImportInterface(
        const QString& service, const QString& path,
        const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieExternalOperationImportInterface::
    ~DeUni_stuttgartVoxieExternalOperationImportInterface() {}

/*
 * Implementation of interface class
 * DeUni_stuttgartVoxieExternalOperationRunFilterInterface
 */

DeUni_stuttgartVoxieExternalOperationRunFilterInterface::
    DeUni_stuttgartVoxieExternalOperationRunFilterInterface(
        const QString& service, const QString& path,
        const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieExternalOperationRunFilterInterface::
    ~DeUni_stuttgartVoxieExternalOperationRunFilterInterface() {}

/*
 * Implementation of interface class
 * DeUni_stuttgartVoxieExternalOperationRunSegmentationStepInterface
 */

DeUni_stuttgartVoxieExternalOperationRunSegmentationStepInterface::
    DeUni_stuttgartVoxieExternalOperationRunSegmentationStepInterface(
        const QString& service, const QString& path,
        const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieExternalOperationRunSegmentationStepInterface::
    ~DeUni_stuttgartVoxieExternalOperationRunSegmentationStepInterface() {}

/*
 * Implementation of interface class DeUni_stuttgartVoxieExternalTaskInterface
 */

DeUni_stuttgartVoxieExternalTaskInterface::
    DeUni_stuttgartVoxieExternalTaskInterface(const QString& service,
                                              const QString& path,
                                              const QDBusConnection& connection,
                                              QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieExternalTaskInterface::
    ~DeUni_stuttgartVoxieExternalTaskInterface() {}

/*
 * Implementation of interface class DeUni_stuttgartVoxieFileDataInterface
 */

DeUni_stuttgartVoxieFileDataInterface::DeUni_stuttgartVoxieFileDataInterface(
    const QString& service, const QString& path,
    const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieFileDataInterface::
    ~DeUni_stuttgartVoxieFileDataInterface() {}

/*
 * Implementation of interface class
 * DeUni_stuttgartVoxieFileDataByteStreamInterface
 */

DeUni_stuttgartVoxieFileDataByteStreamInterface::
    DeUni_stuttgartVoxieFileDataByteStreamInterface(
        const QString& service, const QString& path,
        const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieFileDataByteStreamInterface::
    ~DeUni_stuttgartVoxieFileDataByteStreamInterface() {}

/*
 * Implementation of interface class DeUni_stuttgartVoxieFilterNodeInterface
 */

DeUni_stuttgartVoxieFilterNodeInterface::
    DeUni_stuttgartVoxieFilterNodeInterface(const QString& service,
                                            const QString& path,
                                            const QDBusConnection& connection,
                                            QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieFilterNodeInterface::
    ~DeUni_stuttgartVoxieFilterNodeInterface() {}

/*
 * Implementation of interface class DeUni_stuttgartVoxieFilterObjectInterface
 */

DeUni_stuttgartVoxieFilterObjectInterface::
    DeUni_stuttgartVoxieFilterObjectInterface(const QString& service,
                                              const QString& path,
                                              const QDBusConnection& connection,
                                              QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieFilterObjectInterface::
    ~DeUni_stuttgartVoxieFilterObjectInterface() {}

/*
 * Implementation of interface class
 * DeUni_stuttgartVoxieGeometricPrimitiveDataInterface
 */

DeUni_stuttgartVoxieGeometricPrimitiveDataInterface::
    DeUni_stuttgartVoxieGeometricPrimitiveDataInterface(
        const QString& service, const QString& path,
        const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieGeometricPrimitiveDataInterface::
    ~DeUni_stuttgartVoxieGeometricPrimitiveDataInterface() {}

/*
 * Implementation of interface class
 * DeUni_stuttgartVoxieGeometricPrimitiveTypeInterface
 */

DeUni_stuttgartVoxieGeometricPrimitiveTypeInterface::
    DeUni_stuttgartVoxieGeometricPrimitiveTypeInterface(
        const QString& service, const QString& path,
        const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieGeometricPrimitiveTypeInterface::
    ~DeUni_stuttgartVoxieGeometricPrimitiveTypeInterface() {}

/*
 * Implementation of interface class DeUni_stuttgartVoxieGuiInterface
 */

DeUni_stuttgartVoxieGuiInterface::DeUni_stuttgartVoxieGuiInterface(
    const QString& service, const QString& path,
    const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieGuiInterface::~DeUni_stuttgartVoxieGuiInterface() {}

/*
 * Implementation of interface class DeUni_stuttgartVoxieImageDataPixelInterface
 */

DeUni_stuttgartVoxieImageDataPixelInterface::
    DeUni_stuttgartVoxieImageDataPixelInterface(
        const QString& service, const QString& path,
        const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieImageDataPixelInterface::
    ~DeUni_stuttgartVoxieImageDataPixelInterface() {}

/*
 * Implementation of interface class DeUni_stuttgartVoxieImporterInterface
 */

DeUni_stuttgartVoxieImporterInterface::DeUni_stuttgartVoxieImporterInterface(
    const QString& service, const QString& path,
    const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieImporterInterface::
    ~DeUni_stuttgartVoxieImporterInterface() {}

/*
 * Implementation of interface class
 * DeUni_stuttgartVoxieImporterPropertyInterface
 */

DeUni_stuttgartVoxieImporterPropertyInterface::
    DeUni_stuttgartVoxieImporterPropertyInterface(
        const QString& service, const QString& path,
        const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieImporterPropertyInterface::
    ~DeUni_stuttgartVoxieImporterPropertyInterface() {}

/*
 * Implementation of interface class DeUni_stuttgartVoxieInstanceInterface
 */

DeUni_stuttgartVoxieInstanceInterface::DeUni_stuttgartVoxieInstanceInterface(
    const QString& service, const QString& path,
    const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieInstanceInterface::
    ~DeUni_stuttgartVoxieInstanceInterface() {}

/*
 * Implementation of interface class DeUni_stuttgartVoxieNodeInterface
 */

DeUni_stuttgartVoxieNodeInterface::DeUni_stuttgartVoxieNodeInterface(
    const QString& service, const QString& path,
    const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieNodeInterface::~DeUni_stuttgartVoxieNodeInterface() {}

/*
 * Implementation of interface class DeUni_stuttgartVoxieNodePropertyInterface
 */

DeUni_stuttgartVoxieNodePropertyInterface::
    DeUni_stuttgartVoxieNodePropertyInterface(const QString& service,
                                              const QString& path,
                                              const QDBusConnection& connection,
                                              QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieNodePropertyInterface::
    ~DeUni_stuttgartVoxieNodePropertyInterface() {}

/*
 * Implementation of interface class DeUni_stuttgartVoxieNodePrototypeInterface
 */

DeUni_stuttgartVoxieNodePrototypeInterface::
    DeUni_stuttgartVoxieNodePrototypeInterface(
        const QString& service, const QString& path,
        const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieNodePrototypeInterface::
    ~DeUni_stuttgartVoxieNodePrototypeInterface() {}

/*
 * Implementation of interface class DeUni_stuttgartVoxieObjectInterface
 */

DeUni_stuttgartVoxieObjectInterface::DeUni_stuttgartVoxieObjectInterface(
    const QString& service, const QString& path,
    const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieObjectInterface::~DeUni_stuttgartVoxieObjectInterface() {}

/*
 * Implementation of interface class DeUni_stuttgartVoxieObjectPropertyInterface
 */

DeUni_stuttgartVoxieObjectPropertyInterface::
    DeUni_stuttgartVoxieObjectPropertyInterface(
        const QString& service, const QString& path,
        const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieObjectPropertyInterface::
    ~DeUni_stuttgartVoxieObjectPropertyInterface() {}

/*
 * Implementation of interface class
 * DeUni_stuttgartVoxieObjectPrototypeInterface
 */

DeUni_stuttgartVoxieObjectPrototypeInterface::
    DeUni_stuttgartVoxieObjectPrototypeInterface(
        const QString& service, const QString& path,
        const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieObjectPrototypeInterface::
    ~DeUni_stuttgartVoxieObjectPrototypeInterface() {}

/*
 * Implementation of interface class DeUni_stuttgartVoxieOperationInterface
 */

DeUni_stuttgartVoxieOperationInterface::DeUni_stuttgartVoxieOperationInterface(
    const QString& service, const QString& path,
    const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieOperationInterface::
    ~DeUni_stuttgartVoxieOperationInterface() {}

/*
 * Implementation of interface class
 * DeUni_stuttgartVoxieOperationResultInterface
 */

DeUni_stuttgartVoxieOperationResultInterface::
    DeUni_stuttgartVoxieOperationResultInterface(
        const QString& service, const QString& path,
        const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieOperationResultInterface::
    ~DeUni_stuttgartVoxieOperationResultInterface() {}

/*
 * Implementation of interface class
 * DeUni_stuttgartVoxieOperationResultImportInterface
 */

DeUni_stuttgartVoxieOperationResultImportInterface::
    DeUni_stuttgartVoxieOperationResultImportInterface(
        const QString& service, const QString& path,
        const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieOperationResultImportInterface::
    ~DeUni_stuttgartVoxieOperationResultImportInterface() {}

/*
 * Implementation of interface class
 * DeUni_stuttgartVoxieOperationResultImportNodeInterface
 */

DeUni_stuttgartVoxieOperationResultImportNodeInterface::
    DeUni_stuttgartVoxieOperationResultImportNodeInterface(
        const QString& service, const QString& path,
        const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieOperationResultImportNodeInterface::
    ~DeUni_stuttgartVoxieOperationResultImportNodeInterface() {}

/*
 * Implementation of interface class
 * DeUni_stuttgartVoxieOperationResultImportObjectInterface
 */

DeUni_stuttgartVoxieOperationResultImportObjectInterface::
    DeUni_stuttgartVoxieOperationResultImportObjectInterface(
        const QString& service, const QString& path,
        const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieOperationResultImportObjectInterface::
    ~DeUni_stuttgartVoxieOperationResultImportObjectInterface() {}

/*
 * Implementation of interface class DeUni_stuttgartVoxiePluginInterface
 */

DeUni_stuttgartVoxiePluginInterface::DeUni_stuttgartVoxiePluginInterface(
    const QString& service, const QString& path,
    const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxiePluginInterface::~DeUni_stuttgartVoxiePluginInterface() {}

/*
 * Implementation of interface class DeUni_stuttgartVoxiePropertyInterface
 */

DeUni_stuttgartVoxiePropertyInterface::DeUni_stuttgartVoxiePropertyInterface(
    const QString& service, const QString& path,
    const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxiePropertyInterface::
    ~DeUni_stuttgartVoxiePropertyInterface() {}

/*
 * Implementation of interface class DeUni_stuttgartVoxiePropertyTypeInterface
 */

DeUni_stuttgartVoxiePropertyTypeInterface::
    DeUni_stuttgartVoxiePropertyTypeInterface(const QString& service,
                                              const QString& path,
                                              const QDBusConnection& connection,
                                              QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxiePropertyTypeInterface::
    ~DeUni_stuttgartVoxiePropertyTypeInterface() {}

/*
 * Implementation of interface class DeUni_stuttgartVoxieSeriesDataInterface
 */

DeUni_stuttgartVoxieSeriesDataInterface::
    DeUni_stuttgartVoxieSeriesDataInterface(const QString& service,
                                            const QString& path,
                                            const QDBusConnection& connection,
                                            QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieSeriesDataInterface::
    ~DeUni_stuttgartVoxieSeriesDataInterface() {}

/*
 * Implementation of interface class
 * DeUni_stuttgartVoxieSeriesDimensionInterface
 */

DeUni_stuttgartVoxieSeriesDimensionInterface::
    DeUni_stuttgartVoxieSeriesDimensionInterface(
        const QString& service, const QString& path,
        const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieSeriesDimensionInterface::
    ~DeUni_stuttgartVoxieSeriesDimensionInterface() {}

/*
 * Implementation of interface class DeUni_stuttgartVoxieSurfaceDataInterface
 */

DeUni_stuttgartVoxieSurfaceDataInterface::
    DeUni_stuttgartVoxieSurfaceDataInterface(const QString& service,
                                             const QString& path,
                                             const QDBusConnection& connection,
                                             QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieSurfaceDataInterface::
    ~DeUni_stuttgartVoxieSurfaceDataInterface() {}

/*
 * Implementation of interface class
 * DeUni_stuttgartVoxieSurfaceDataTriangleIndexedInterface
 */

DeUni_stuttgartVoxieSurfaceDataTriangleIndexedInterface::
    DeUni_stuttgartVoxieSurfaceDataTriangleIndexedInterface(
        const QString& service, const QString& path,
        const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieSurfaceDataTriangleIndexedInterface::
    ~DeUni_stuttgartVoxieSurfaceDataTriangleIndexedInterface() {}

/*
 * Implementation of interface class DeUni_stuttgartVoxieTableDataInterface
 */

DeUni_stuttgartVoxieTableDataInterface::DeUni_stuttgartVoxieTableDataInterface(
    const QString& service, const QString& path,
    const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieTableDataInterface::
    ~DeUni_stuttgartVoxieTableDataInterface() {}

/*
 * Implementation of interface class DeUni_stuttgartVoxieTaskInterface
 */

DeUni_stuttgartVoxieTaskInterface::DeUni_stuttgartVoxieTaskInterface(
    const QString& service, const QString& path,
    const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieTaskInterface::~DeUni_stuttgartVoxieTaskInterface() {}

/*
 * Implementation of interface class
 * DeUni_stuttgartVoxieTomographyRawDataInterface
 */

DeUni_stuttgartVoxieTomographyRawDataInterface::
    DeUni_stuttgartVoxieTomographyRawDataInterface(
        const QString& service, const QString& path,
        const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieTomographyRawDataInterface::
    ~DeUni_stuttgartVoxieTomographyRawDataInterface() {}

/*
 * Implementation of interface class
 * DeUni_stuttgartVoxieTomographyRawData2DAccessorInterface
 */

DeUni_stuttgartVoxieTomographyRawData2DAccessorInterface::
    DeUni_stuttgartVoxieTomographyRawData2DAccessorInterface(
        const QString& service, const QString& path,
        const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieTomographyRawData2DAccessorInterface::
    ~DeUni_stuttgartVoxieTomographyRawData2DAccessorInterface() {}

/*
 * Implementation of interface class
 * DeUni_stuttgartVoxieTomographyRawData2DAccessorOperationsInterface
 */

DeUni_stuttgartVoxieTomographyRawData2DAccessorOperationsInterface::
    DeUni_stuttgartVoxieTomographyRawData2DAccessorOperationsInterface(
        const QString& service, const QString& path,
        const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieTomographyRawData2DAccessorOperationsInterface::
    ~DeUni_stuttgartVoxieTomographyRawData2DAccessorOperationsInterface() {}

/*
 * Implementation of interface class
 * DeUni_stuttgartVoxieTomographyRawData2DRegularInterface
 */

DeUni_stuttgartVoxieTomographyRawData2DRegularInterface::
    DeUni_stuttgartVoxieTomographyRawData2DRegularInterface(
        const QString& service, const QString& path,
        const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieTomographyRawData2DRegularInterface::
    ~DeUni_stuttgartVoxieTomographyRawData2DRegularInterface() {}

/*
 * Implementation of interface class
 * DeUni_stuttgartVoxieTomographyRawDataAccessorInterface
 */

DeUni_stuttgartVoxieTomographyRawDataAccessorInterface::
    DeUni_stuttgartVoxieTomographyRawDataAccessorInterface(
        const QString& service, const QString& path,
        const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieTomographyRawDataAccessorInterface::
    ~DeUni_stuttgartVoxieTomographyRawDataAccessorInterface() {}

/*
 * Implementation of interface class
 * DeUni_stuttgartVoxieTomographyRawDataBaseInterface
 */

DeUni_stuttgartVoxieTomographyRawDataBaseInterface::
    DeUni_stuttgartVoxieTomographyRawDataBaseInterface(
        const QString& service, const QString& path,
        const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieTomographyRawDataBaseInterface::
    ~DeUni_stuttgartVoxieTomographyRawDataBaseInterface() {}

/*
 * Implementation of interface class DeUni_stuttgartVoxieUtilitiesInterface
 */

DeUni_stuttgartVoxieUtilitiesInterface::DeUni_stuttgartVoxieUtilitiesInterface(
    const QString& service, const QString& path,
    const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieUtilitiesInterface::
    ~DeUni_stuttgartVoxieUtilitiesInterface() {}

/*
 * Implementation of interface class DeUni_stuttgartVoxieVisualizerNodeInterface
 */

DeUni_stuttgartVoxieVisualizerNodeInterface::
    DeUni_stuttgartVoxieVisualizerNodeInterface(
        const QString& service, const QString& path,
        const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieVisualizerNodeInterface::
    ~DeUni_stuttgartVoxieVisualizerNodeInterface() {}

/*
 * Implementation of interface class
 * DeUni_stuttgartVoxieVisualizerObjectInterface
 */

DeUni_stuttgartVoxieVisualizerObjectInterface::
    DeUni_stuttgartVoxieVisualizerObjectInterface(
        const QString& service, const QString& path,
        const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieVisualizerObjectInterface::
    ~DeUni_stuttgartVoxieVisualizerObjectInterface() {}

/*
 * Implementation of interface class DeUni_stuttgartVoxieVolumeDataInterface
 */

DeUni_stuttgartVoxieVolumeDataInterface::
    DeUni_stuttgartVoxieVolumeDataInterface(const QString& service,
                                            const QString& path,
                                            const QDBusConnection& connection,
                                            QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieVolumeDataInterface::
    ~DeUni_stuttgartVoxieVolumeDataInterface() {}

/*
 * Implementation of interface class
 * DeUni_stuttgartVoxieVolumeDataBlockInterface
 */

DeUni_stuttgartVoxieVolumeDataBlockInterface::
    DeUni_stuttgartVoxieVolumeDataBlockInterface(
        const QString& service, const QString& path,
        const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieVolumeDataBlockInterface::
    ~DeUni_stuttgartVoxieVolumeDataBlockInterface() {}

/*
 * Implementation of interface class
 * DeUni_stuttgartVoxieVolumeDataBlockJpegInterface
 */

DeUni_stuttgartVoxieVolumeDataBlockJpegInterface::
    DeUni_stuttgartVoxieVolumeDataBlockJpegInterface(
        const QString& service, const QString& path,
        const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieVolumeDataBlockJpegInterface::
    ~DeUni_stuttgartVoxieVolumeDataBlockJpegInterface() {}

/*
 * Implementation of interface class
 * DeUni_stuttgartVoxieVolumeDataVoxelInterface
 */

DeUni_stuttgartVoxieVolumeDataVoxelInterface::
    DeUni_stuttgartVoxieVolumeDataVoxelInterface(
        const QString& service, const QString& path,
        const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieVolumeDataVoxelInterface::
    ~DeUni_stuttgartVoxieVolumeDataVoxelInterface() {}

/*
 * Implementation of interface class
 * DeUni_stuttgartVoxieVolumeSeriesDataInterface
 */

DeUni_stuttgartVoxieVolumeSeriesDataInterface::
    DeUni_stuttgartVoxieVolumeSeriesDataInterface(
        const QString& service, const QString& path,
        const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieVolumeSeriesDataInterface::
    ~DeUni_stuttgartVoxieVolumeSeriesDataInterface() {}

/*
 * Implementation of interface class
 * DeUni_stuttgartVoxieVolumeStructureInterface
 */

DeUni_stuttgartVoxieVolumeStructureInterface::
    DeUni_stuttgartVoxieVolumeStructureInterface(
        const QString& service, const QString& path,
        const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieVolumeStructureInterface::
    ~DeUni_stuttgartVoxieVolumeStructureInterface() {}

/*
 * Implementation of interface class
 * DeUni_stuttgartVoxieVolumeStructureVoxelInterface
 */

DeUni_stuttgartVoxieVolumeStructureVoxelInterface::
    DeUni_stuttgartVoxieVolumeStructureVoxelInterface(
        const QString& service, const QString& path,
        const QDBusConnection& connection, QObject* parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection,
                             parent) {}

DeUni_stuttgartVoxieVolumeStructureVoxelInterface::
    ~DeUni_stuttgartVoxieVolumeStructureVoxelInterface() {}
